### ISSUE TITLE
System.InvalidOperationException: The project already transitively references the target project

### ISSUE THREAD

**Issue by ladsaylee** [dotnet/upgrade-assistant#1016]
I am trying to migrate .NetFramework 4.7.2 to .NET 6 using the Upgrade Assistant.
I was able to successfully migrate full projects. However for one project the Upgrade assistant fails wit following Exception-

### Exceptions (if any)
<C:\Users\1437070\source\repos\Griffin_4_00_000_m\source\Next Service Manager\DM - diagnostic manager>upgrade-assistant upgrade .\DM.sln
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.3.261602+efb3cc30a24e699e6e4337f263a2b9478f04f618

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

[18:02:09 INF] Loaded 5 extensions
[18:02:10 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.101\
[18:02:10 INF] Using Visual Studio install from C:\Program Files\Microsoft Visual Studio\2022\Community [v17]
[18:02:14 ERR] Unexpected error
System.InvalidOperationException: The project already transitively references the target project.
   at Microsoft.CodeAnalysis.Solution.CheckCircularProjectReferences(ProjectId projectId, IReadOnlyCollection`1 projectReferences)
   at Microsoft.CodeAnalysis.Solution.AddProjectReferences(ProjectId projectId, IEnumerable`1 projectReferences)
   at Microsoft.CodeAnalysis.Solution.AddProjectReference(ProjectId projectId, ProjectReference projectReference)
   at Microsoft.CodeAnalysis.Project.AddProjectReference(ProjectReference projectReference)
   at Microsoft.CodeAnalysis.Workspace.UpdateReferencesAfterAdd(Solution solution)
   at Microsoft.CodeAnalysis.Workspace.UpdateReferencesAfterAdd()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenSolutionAsync(String solutionFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildWorkspaceUpgradeContext.GetMsBuildWorkspaceAsync(CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildWorkspaceUpgradeContext.cs:line 179
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildWorkspaceUpgradeContext.InitializeWorkspace(CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildWorkspaceUpgradeContext.cs:line 167
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildUpgradeContextFactory.CreateContext(CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildUpgradeContextFactory.cs:line 30
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 50
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 61>

It will be great if some one points out on how do I proceed ahead.

### Further technical details
- Windows version  (64-bit)

**Comment by sunandabalu** [comment]
@twsouthwick Could this be related to what you are trying to address with #1007 ?

**Comment by sunandabalu** [comment]
@ladsaylee Looks like the issue is while loading the project in question by Roslyn Workspace, could you provide the project file or the solution if possible so we can try to repro it?

**Comment by twsouthwick** [comment]
This is unrelated to the fix in 1007. We'd need more details for the project file

**Comment by ladsaylee** [comment]
I can share the project since it is due to certain policies. However when I manual converted it to .NET SDK and then to .NET Core it worked.
