### ISSUE TITLE
Unexpected error occured when trying to analyze a .net framework project

### ISSUE THREAD

**Issue by Szajkop** [dotnet/upgrade-assistant#1042]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

PM> upgrade-assistant analyze MySolution.sln 
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.3.310302+ff68dbd874aeeb5b1746d225812a057aac0e7e62

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

[12:15:39 INF] Loaded 6 extensions
[12:15:39 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.100\
[12:15:39 INF] Using Visual Studio install from C:\Program Files\Microsoft Visual Studio\2022\Enterprise [v17]
[12:15:43 ERR] Unexpected error
Microsoft.Extensions.Options.OptionsValidationException: DataAnnotation validation failed for members: 'Format' with the error: 'The Format field is required.'.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleAnalyze.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Analyze/ConsoleAnalyze.cs:line 64
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 61
PM>

**Comment by p-roman** [comment]
I'm also running into this same issue when running the upgrade assistant on a .NET Framework 4.8 Class library.

**Comment by sunandabalu** [comment]
Taking a look

**Comment by p-roman** [comment]
Thanks, but it looks like the pipeline build of this fix failed...

**Comment by sunandabalu** [comment]
> Thanks, but it looks like the pipeline build of this fix failed...

@p-roman yes, coz the buildpools running the PR builds were backed up really bad. The internal CI build with the merge was green as you can see from the build status in the ReadMe.
