### ISSUE TITLE
dotnet tool install fails with "Version string portion was too short or too long. (Parameter 'input')"

### ISSUE THREAD

**Issue by HighPerfDotNet** [dotnet/upgrade-assistant#1046]
Trying to install using **_dotnet tool install -g upgrade-assistant_** and getting Exception - 

"Unhandled exception: System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c.<Execute>b__17_1(NuGetFramework f)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()"

dotnet tool search lists available tool as - 

Package ID                                         Latest Version      Authors                   Downloads      Verified
------------------------------------------------------------------------------------------------------------------------
upgrade-assistant                                  0.3.310801          Microsoft                 65824

### Further technical details
Current Windows 10, 64 bit
Visual Studio 2022 with current .NET 6

SDKs -

3.1.416 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.210 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.405 [C:\Program Files\dotnet\sdk]
6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]
6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
6.0.102 [C:\Program Files\dotnet\sdk]
6.0.200-preview.21623.6 [C:\Program Files\dotnet\sdk]
6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]
7.0.100-alpha.1.21568.2 [C:\Program Files\dotnet\sdk]

**Comment by HighPerfDotNet** [comment]
Removal of 7.0.0-alpha.1.21567.1 SDK enabled install of upgrade-assistant - looks like the problem was with the SDK
