### ISSUE TITLE
ArgumentNullException in "Apply fix for UA0002: Types should be upgraded"

### ISSUE THREAD

**Issue by XalbatEcheverria** [dotnet/upgrade-assistant#1063]
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory
Can't upload the .clef file here, it says the format is unsupported.

### Describe the bug
Trying to upgrade a project from .net 4.6.1 to .net 6. I can't provide the full project, but might be able to share the .csproj if needed

### Exceptions (if any)

```
[15:50:25 INF] Applying upgrade step Apply fix for UA0002: Types should be upgraded
[15:50:25 ERR] Unexpected error applying step
System.ArgumentNullException: Value cannot be null. (Parameter 'document')
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.TryFixDiagnosticAsync(Diagnostic diagnostic, Document document, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178
```

### Further technical details
- Windows version and bitness info : Windows 10 21h2 - 64-bit
- `dotnet --list-sdks`
![image](https://user-images.githubusercontent.com/36201002/156007417-eeab8635-8832-4531-a970-f14ffe9ea7c2.png)

- `upgrade-assistant --version`
![image](https://user-images.githubusercontent.com/36201002/156007480-c5428811-8522-4582-826d-27aaecb884f3.png)

**Comment by sunandabalu** [comment]
@XalbatEcheverria Are you trying to convert cshtml pages to razor documents? we have an issue tracking the bug for that here - https://github.com/dotnet/upgrade-assistant/issues/893

**Comment by XalbatEcheverria** [comment]
@sunandabalu Yes I am, do you think these two errors could be related ?
What do you advise me to do to continue my migration, ignoring the error and change these files manually ?

**Comment by sunandabalu** [comment]
> @sunandabalu Yes I am, do you think these two errors could be related ? What do you advise me to do to continue my migration, ignoring the error and change these files manually ?

Likely they are related. @mjrousos could you provide some insight here for razor upgrade?
