### ISSUE TITLE
Access Denied error at second step "Convert project file to SDK style"

### ISSUE THREAD

**Issue by SriniDasari** [dotnet/upgrade-assistant#1096]
I'm trying to update a simple class library project from .net framework 4.7.1 to .net 6. Getting access denied error at second step "Convert project file to SDK style". 

[20:21:38 ERR] Unexpected error applying step
System.UnauthorizedAccessException: Access to the path 'C:\Srini\Projects\MercerGlobe\Globe-Upgrade\Old_Projects\Components\Mercer.MCOOL.Admin\Mercer.MCOOL.Admin.csproj' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at MSBuild.Abstractions.MSBuildConversionWorkspace.RemoveTargetsNotLoadableByNETSDKMSBuild(String path) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs:line 115
   at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs:line 43
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspaceLoader.cs:line 45
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertInProcessTool.RunAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.RunTryConvertAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.ApplyAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178

**Comment by sunandabalu** [comment]
@SriniDasari Looks like the tool is not able to access the project file, maybe could you try running it against the project in a different folder?

**Comment by SriniDasari** [comment]
@sunandabalu . Thanks for quick reply. 
I just tried to take a chance by unticking the default check on the read only checkbox in the properties of the project root folder and it worked.
