### ISSUE TITLE
 [Failed] Clean up NuGet package references

### ISSUE THREAD

**Issue by yucapro** [dotnet/upgrade-assistant#1101]
[11:02:19 ERR] Unexpected error
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.PackageConfig.GetPackages(String path)+MoveNext() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/PackageConfig.cs:line 13
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.IsTransitivelyAvailableAsync(String packageName, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 72
   at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 83
   at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 81
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetGeneralProjectComponentsAsync(IProject project, IProjectFile file, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/ComponentIdentifier.cs:line 91
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetComponentsAsync(IProject project, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/ComponentIdentifier.cs:line 25
   at Microsoft.DotNet.UpgradeAssistant.ProjectExtensions.AppliesToProjectAsync(Type type, IProject project, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/ProjectExtensions.cs:line 60
   at Microsoft.DotNet.UpgradeAssistant.Steps.Configuration.ConfigUpdaterSubStep.IsApplicableImplAsync(IUpgradeContext context, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.IsApplicableAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 222
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.<>c__DisplayClass13_0.<<ShowUpgradeStepsAsync>b__0>d.MoveNext() in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 157
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIteratorWithTask`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:line 277
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 157
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 157
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 171
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 157
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 66
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 78
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 62

**Comment by sunandabalu** [comment]
@yucapro Thanks for filing the issue. What kind of project are you trying to upgrade? Could you share the .csproj if possible along with the full upgrade-assisteant.clef` file?

**Comment by yucapro** [comment]
@sunandabalu Thanks for getting back to me. The project upgrade didn't work. I simply started an new, empty .Net 6 project and manually moved over all the .cs files, then converted the structure from .Net 4.8 to Core 6. It was a bit painful, but I got it done in two days.

**Comment by sunandabalu** [comment]
> @sunandabalu Thanks for getting back to me. The project upgrade didn't work. I simply started an new, empty .Net 6 project and manually moved over all the .cs files, then converted the structure from .Net 4.8 to Core 6. It was a bit painful, but I got it done in two days.

Oh wow that is great that you were to get it upgraded in 2 days! Curious to know what kind of project you were trying though so we can see what can be done in UA.
