### ISSUE TITLE
Error in WinUIApiAlertCodeFixer due to use of Linq First()

### ISSUE THREAD

**Issue by paul-schroeder2** [dotnet/upgrade-assistant#1156]
### Describe the bug
Received the following error:

Applying upgrade step Apply fix for [UA306_A1, UA306_A2, UA306_A3, UA306_A4, UA306_B, UA306_C, UA306_D, UA306_E, UA306_F, UA306_G, UA306_H, UA306_I]: Replace usage of Windows.UI.Core.CoreDispatcher, Replace usage of Window.Current.Dispatcher, Replace usage of App.Window.Dispatcher, Replace usage of Window.Dispatcher, Replace usage of Windows.Media.Capture.CameraCaptureUI, Replace usage of Micorsoft.UI.Xaml.Controls.InkCanvas, Replace usage of Microsoft.UI.Xaml.Controls.Maps.MapControl, Replace usage of Microsoft.UI.Xaml.Controls.MediaElement, Replace usage of Windows.Graphics.Printing.PrintManager, Replace usage of Windows.Security.Authentication.Web.WebAuthenticationBroker, Replace usage of Windows.UI.Xaml.Media.AcrylicBrush.BackgroundSource, Replace usage of Windows.UI.Shell.TaskbarManager
[22:52:33 ERR] Unexpected error applying step
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.WinUIApiAlertCodeFixer.RegisterCodeFixesAsync(CodeFixContext context)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.TryFixDiagnosticAsync(Diagnostic diagnostic, Document document, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in C:\Code_Tmp\dotnet\upgrade-assistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\UpgradeStep.cs:line 178

![image](https://user-images.githubusercontent.com/107234768/172991447-1e6ba085-668e-4657-a69b-c3f5d97ccfa2.png)

#### with a stack trace of:

   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.WinUIApiAlertCodeFixer.<RegisterCodeFixesAsync>d__5.MoveNext() in C:\Code_Tmp\dotnet\upgrade-assistant\src\extensions\windows\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows\UWPtoWinAppSDKUpgrade\WinUIApiAlertCodeFixer.cs:line 69
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.<TryFixDiagnosticAsync>d__17.MoveNext() in C:\Code_Tmp\dotnet\upgrade-assistant\src\extensions\default\Microsoft.DotNet.UpgradeAssistant.Steps.Source\CodeFixerStep.cs:line 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.<ApplyImplAsync>d__16.MoveNext() in C:\Code_Tmp\dotnet\upgrade-assistant\src\extensions\default\Microsoft.DotNet.UpgradeAssistant.Steps.Source\CodeFixerStep.cs:line 105
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.<ApplyAsync>d__46.MoveNext() in C:\Code_Tmp\dotnet\upgrade-assistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\UpgradeStep.cs:line 178

### To Reproduce
Upgrade my UWP project containing this file:  LiveAI.Desi.Forms.UWP\Renderers\CustomCollectionViewRenderer.cs

![image](https://user-images.githubusercontent.com/107234768/172991419-64c4a0fa-a1fe-4ef7-86bd-454c4ab7e9fa.png)

### Exceptions (if any)
System.InvalidOperationException: Sequence contains no elements

[22:52:33 ERR] Unexpected error applying step
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.WinUIApiAlertCodeFixer.RegisterCodeFixesAsync(CodeFixContext context)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.TryFixDiagnosticAsync(Diagnostic diagnostic, Document document, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in C:\Code_Tmp\dotnet\upgrade-assistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\UpgradeStep.cs:line 178

### Further technical details
- Win 11, 64-bit
- VS 2022 Preview
-  `dotnet --list-sdks`

2.1.818 [C:\Program Files\dotnet\sdk]
3.1.419 [C:\Program Files\dotnet\sdk]
5.0.405 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]
7.0.100-preview.2.22153.17 [C:\Program Files\dotnet\sdk]
7.0.100-preview.4.22252.9 [C:\Program Files\dotnet\sdk]

- Include the output of `upgrade-assistant --version`
0.3.330701+fa00bab2d06aab9c710c344c0f32440ad4eb8410

**Comment by ujjwalchadha** [comment]
Dup of #1153

**Comment by sunandabalu** [comment]
Dup of https://github.com/dotnet/upgrade-assistant/issues/1153
