### ISSUE TITLE
 Unexpected error during upgrade. Microsoft.Build.Exceptions.InvalidProjectFileException:

### ISSUE THREAD

**Issue by SebastianBeckerDev** [dotnet/upgrade-assistant#1189]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

HI Team

I installed VS2022 Preview (in parallel to the VS2022 and VS2019). I created the sample MAUI project - it compiled fine on Windows. Then I wanted to take my Xamarin project and run it through the .NET Upgrade assistant analyzer. Unfortunately it ran into an error loading a project from the solution. Here is the output:

-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.231403+ee9618b1fb94a6881a2e38a7b2ad50356ba54465 -
-----------------------------------------------------------------------------------------

[20:53:58 INF] Loaded 2 extensions
[20:53:58 INF] MSBuild registered from C:\Program Files\dotnet\sdk\5.0.408\
[20:53:59 WRN] The Analyze command feature is still under development, expect things to be not fully functional at the moment
[20:54:06 INF] Marking package Newtonsoft.Json for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package System.ServiceModel.Duplex for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package System.ServiceModel.Http for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package System.ServiceModel.NetTcp for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package System.ServiceModel.Primitives for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package System.ServiceModel.Security for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package Xamarin.Essentials for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package Xamarin.Forms for removal because it appears to be a transitive dependency
[20:54:06 INF] Marking package Xamarin.Forms.Visual.Material for removal because it appears to be a transitive dependency
[20:54:06 WRN] .NET Upgrade Assistant analyzer NuGet package reference cannot be added because the package cannot be found
[20:54:06 INF] Package Analysis for ineXs.csproj for the target TFM of netstandard2.0
[20:54:06 INF] Packages to be removed: Newtonsoft.Json, Version=13.0.1
System.ServiceModel.Duplex, Version=4.9.0
System.ServiceModel.Http, Version=4.9.0
System.ServiceModel.NetTcp, Version=4.9.0
System.ServiceModel.Primitives, Version=4.9.0
System.ServiceModel.Security, Version=4.9.0
Xamarin.Essentials, Version=1.7.3
Xamarin.Forms, Version=5.0.0.2478
Xamarin.Forms.Visual.Material, Version=5.0.0.2478
[20:54:06 ERR] Unexpected error during upgrade.
Microsoft.Build.Exceptions.InvalidProjectFileException: Das importierte Projekt "C:\Program Files\dotnet\sdk\5.0.408\Xamarin\iOS\Xamarin.iOS.CSharp.targets" wurde nicht gefunden. Stellen Sie sicher, dass der Ausdruck in der Import-Deklaration "C:\Program Files\dotnet\sdk\5.0.408\\Xamarin\iOS\Xamarin.iOS.CSharp.targets" richtig ist und dass die Datei auf dem Datenträger vorhanden ist.  C:\GITMaui\projects\gwk\ineXs\ineXs\ineXs.iOS\ineXs.iOS.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.get_Project() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.cs:line 68
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetPropertyValue(String propertyName) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.File.cs:line 188
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.TargetFrameworkMonikerCollection.GetTfms(IProjectFile file, String propertyName) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/TargetFrameworkMonikerCollection.cs:line 119
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.TargetFrameworkMonikerCollection.GetNonSdkTargetFramework(IProjectFile file) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/TargetFrameworkMonikerCollection.cs:line 106
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.TargetFrameworkMonikerCollection.GetFrameworkMonikers(IProjectFile file) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/TargetFrameworkMonikerCollection.cs:line 88
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.TargetFrameworkMonikerCollection.get_RawValues() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/TargetFrameworkMonikerCollection.cs:line 65
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.TargetFrameworkMonikerCollection.GetEnumerator()+MoveNext() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/TargetFrameworkMonikerCollection.cs:line 76
   at Microsoft.DotNet.UpgradeAssistant.TargetFramework.TargetFrameworkSelector.GetDefaultTargetFrameworkMoniker(IProject project) in /_/src/components/Microsoft.DotNet.UpgradeAssistant/TargetFramework/TargetFrameworkSelector.cs:line 74
   at Microsoft.DotNet.UpgradeAssistant.TargetFramework.TargetFrameworkSelector.SelectTargetFrameworkAsync(IProject project, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant/TargetFramework/TargetFrameworkSelector.cs:line 52
   at Microsoft.DotNet.UpgradeAssistant.Steps.Packages.AnalyzePackageStatus.AnalyzeAsync(AnalyzeContext analysis, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleAnalyze.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleAnalyze.cs:line 41
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.RunCommandAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 86
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 44

I also double checked the filesystem - the csproj file is available on the disk.

Thanks in advance for checking this issue.

**Comment by ghidalgo3** [comment]
In my case, the issue had nothing to do with VS and its workloads. I had a minor syntax error in a `Directory.Build.props` that caused `upgrade-assistant` to fail _but_ it did not prevent VS from loading the project file. Here is the relevant error from the `clef` file:

```
{"@t":"2022-08-03T16:28:56.8897163Z","@mt":"[{Level}] Problem loading file in MSBuild workspace {Message}","@l":"Debug","Level":"Failure","Message":"Msbuild failed when processing the file 'C:\\code\\Prototypes\\src\\PenPump\\PenPump.csproj' with message: Expected a closing quote after position 24 in condition \" '$(Configuration) == '' \".  C:\\code\\Prototypes\\Directory.Build.props","SourceContext":"Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildWorkspaceUpgradeContext"}
```

**Comment by brandonh-msft** [comment]
thanks for that update! Closing.
