### ISSUE TITLE
Version 0.4.346201 throws unhandled exception parsing command line arguments

### ISSUE THREAD

**Issue by mrahl** [dotnet/upgrade-assistant#1297]
- [x] Include the log file `upgrade-assistant.clef` that is produced in the working directory

`{"@t":"2022-09-16T12:45:04.6502249Z","@mt":"Hosting starting","@l":"Debug","EventId":{"Id":1,"Name":"Starting"},"SourceContext":"Microsoft.Extensions.Hosting.Internal.Host"}`

### Describe the bug
After updating upgrade assistant to the latest version (0.4.346201) and trying to launch it with the `--extension` switch it throws an unhandled exception.

- Going back to the previous version (0.4.336902), it does not have this issue. It works fine with my extension.
- If I omit the --extension argument I also don't run into the issue.
- If I give the extension argument a path to a nonexisting or empty folder, I still get the same exception. So it does not seem to relate to the contents of my extension.
-  Similarly, if I give the path to a csproj file that does not exist, I still get the same exception.
 
This, together with the stack trace of the exception (see below), seems to indicate that it is the argument parsing itself that fails.

### To Reproduce

The contents of the csproj or the extension does not seem to matter, it doesn't even have to exist and the behavior is still the same.

Update the tool to version 0.4.346201 and launch it with the --extension argument.

```
upgrade-assistant upgrade "Project.csproj" --extension "C:\Dev\my-extension"
```

### Exceptions (if any)

```
Unhandled exception. System.ArgumentException: Type System.Collections.Generic.IReadOnlyCollection`1[System.String] cannot be created without a custom binder.
   at System.CommandLine.Binding.ArgumentConverter.CreateEnumerable(Type type, Type itemType, Int32 capacity)
   at System.CommandLine.Binding.ArgumentConverter.ConvertTokens(Argument argument, Type type, IReadOnlyList`1 tokens, LocalizationResources localizationResources, ArgumentResult argumentResult)
   at System.CommandLine.Binding.ArgumentConverter.TryConvertArgument(ArgumentResult argumentResult, Object& value)
   at System.CommandLine.Parsing.ArgumentResult.Convert(Argument argument)
   at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertOptionResult(OptionResult optionResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop()
   at System.CommandLine.Parsing.ParseResultVisitor.Visit(SyntaxNode node)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Microsoft.DotNet.UpgradeAssistant.Cli.Program.<Main>(String[] args)
```

### Further technical details
- Windows version and bitness info (32-bit or 64-bit): Windows 10 Pro 19044.1889 64 bit
- Include the output of `dotnet --list-sdks` : 

2.0.3 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
2.2.102 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.422 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.402 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.108 [C:\Program Files\dotnet\sdk]

- Include the output of `upgrade-assistant --version` : 0.4.346201+71e7f6e92986df688a9ef901343b24c9ad63ccff

**Comment by kjones** [comment]
Specifying any `--entry-point` argument was failing with the same exception for me. No additional extensions were in use. Downgrade to previous release accepted the argument.
