### ISSUE TITLE
Error : Update WCF service to CoreWCF 

### ISSUE THREAD

**Issue by Norc89** [dotnet/upgrade-assistant#1326]
### Description
I want to migrate WCF service to net 6.0, after i run migration failed on step:
7. [Failed] Update WCF service to CoreWCF (Preview), 

I can not find what could be the reason. I have already google it and i'm not using .Single()

```
 Applying upgrade step Remove package 'System.ServiceModel.NetTcp'
[10:00:18 INF] Removing outdated package reference: System.ServiceModel.NetTcp, Version=4.8.1
[10:00:18 INF] Upgrade step Remove package 'System.ServiceModel.NetTcp' applied successfully
[10:00:18 INF] Applying upgrade step Transitive reference analyzer
[10:00:19 INF] Upgrade step Transitive reference analyzer applied successfully
[10:00:19 INF] Applying upgrade step Update NuGet Packages
[10:00:19 INF] Upgrade step Update NuGet Packages applied successfully
Please press enter to continue...

[10:00:22 INF] Initializing upgrade step Add template files
[10:00:23 INF] 0 expected template items needed
[10:00:23 INF] Initializing upgrade step Update WCF service to CoreWCF (Preview)
[10:00:23 ERR] Unexpected error happened during CoreWCF porting.
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.FindPath(IProject project)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.Initialize(IProject project)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.InitializeImplAsync(IUpgradeContext context, CancellationToken token)

Upgrade Steps

Entrypoint: G:\Source\Vs2022\src\MsaIoService\MsaIoService.csproj
Current Project: G:\Source\Vs2022\src\MsaIoService\MsaIoService.csproj
```

### Exceptions (if any)

```
Unexpected error happened during CoreWCF porting.
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.FindPath(IProject project)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.Initialize(IProject project)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.WCFUpdater.WCFUpdateStep.InitializeImplAsync(IUpgradeContext context, CancellationToken token)
```
![error](https://user-images.githubusercontent.com/23267843/194259013-888276a6-dd38-442d-8177-dbe09f5768fd.jpg)

Upgrade Steps

### Further technical details
- Windows 64 bit
[upgrade-assistant.clef.txt](https://github.com/dotnet/upgrade-assistant/files/9722514/upgrade-assistant.clef.txt) (remove .txt .clef is not supported on upload) 

DotnetList
- 2.2.207 [C:\Program Files\dotnet\sdk]
- 3.1.414 [C:\Program Files\dotnet\sdk]
- 5.0.213 [C:\Program Files\dotnet\sdk]
- 5.0.412 [C:\Program Files\dotnet\sdk]
- 6.0.401 [C:\Program Files\dotnet\sdk]

-upgrade-assistant --version` -> 0.4.346202+66a923ad8212e008d71c1c232bed728c4c7982c1

**Comment by Norc89** [comment]
@brandonh-msft  No comment on this ?

**Comment by brandonh-msft** [comment]
No this bug will be handled by the @dotnet/dotnet-upgrade-assistant-wcf team based on labels, so that's why I labeled it :)
