### ISSUE TITLE
Upgrade fails without a good error message when files are readonly

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/upgrade-assistant#1335]
### Describe the bug
When the packages.config file is readonly (which will frequently be the case when using TFS), the upgrade-assistant throws an exception, instead of either working or giving a nice error message.

### Exceptions (if any)

> System.UnauthorizedAccessException: Access to the path 'C:\whatever\packages.config' is denied.
>    at System.IO.FileSystem.DeleteFile(String fullPath)
>    at System.IO.File.Delete(String path)
>    at MSBuild.Conversion.Project.ProjectRootElementExtensionsForConversion.ConvertAndAddPackages(IProjectRootElement projectRootElement, ProjectStyle projectStyle, String tfm, Boolean removePackagesConfig) in /_/src/MSBuild.Conversion.Project/ProjectRootElementExtensionsForConversion.cs:line 435
>    at MSBuild.Conversion.Project.Converter.ConvertProjectFile() in /_/src/MSBuild.Conversion.Project/Converter.cs:line 39
>    at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertInProcessTool.RunAsync(IUpgradeContext context, IProject project, CancellationToken token)
>    at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.RunTryConvertAsync(IUpgradeContext context, IProject project, CancellationToken token)
>    at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.ApplyAsync(IUpgradeContext context, IProject project, CancellationToken token)
>    at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178

**Comment by icnocop** [comment]
This happens for any read-only file that needs to be updated.

```
System.UnauthorizedAccessException: Access to the path 'xxx.sln' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllLines(String path, String[] contents)
   at Microsoft.UpgradeAssistant.Transformers.SolutionProjectTypeTransformer.ReplaceProjectTypeGuid(String solutionFile, String projectId, String oldGuid, String newGuid)
   at Microsoft.UpgradeAssistant.Transformers.SolutionProjectTypeTransformer.RunAsync(OperationContext context, SliceNode node, CancellationToken cancellationToken)
   at Microsoft.UpgradeAssistant.Operations.Operation.<RunTransformerAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.UpgradeAssistant.Operations.Operation.<RunNodeAsync>d__17.MoveNext()
	info: Done
	Microsoft.UpgradeAssistant.VS.Slices.Transformers.OpenSolutionTransformer
	info: Opening solution 'xxx.sln'.
```

The UI does not display any errors; it makes it seem like it's still processing files when actually it was stopped:

![image](https://user-images.githubusercontent.com/507649/230702100-ad44a1b1-a6da-4aa4-a3d6-c001e404ce74.png)

**Comment by icnocop** [comment]
.NET Upgrade Assistant v0.5.261.51392 also doesn't check out project files from TFS:

![image](https://github.com/dotnet/upgrade-assistant/assets/507649/f2028452-1d7a-4be6-8019-995203b1b7f4)

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\rami.abughazaleh\AppData\Local\Temp\UpgradeAssistant\Projects\0a668280-9c88-438d-a471-65027c7199c1\2023-09-19--14-14-39\UnitTests.csproj' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at MSBuild.Abstractions.MSBuildConversionWorkspace.RemoveTargetsNotLoadableByNETSDKMSBuild(String path)
   at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb, String actualProjectPath)
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb, String actualProjectPath)
   at Microsoft.UpgradeAssistant.TryConvert.Slices.Services.TryConvertService.ConvertAsync(OperationContext context, String projectFilePath, TargetFramework targetFramework, ILogger logger, CancellationToken cancellationToken)

System.UnauthorizedAccessException: Access to the path 'C:\Work\Team\dev\src\UnitTests\UnitTests.csproj' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.UpgradeAssistant.Transformers.ProjectSdkStyleTransformer.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.UpgradeAssistant.Operations.Operation.<RunTransformerAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.UpgradeAssistant.Operations.Operation.<RunNodeTransformersAsync>d__21.MoveNext()
```
