### ISSUE TITLE
Microsoft SARIF Viewer cannot be installed

### ISSUE THREAD

**Issue by jozefizso** [dotnet/upgrade-assistant#1381]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

The upgrade assistant tool has this prerequisites:
* Visual Studio 2022 17.0 or later

The upgrade report requires the VS extension for SARIF Viewer. I downloaded the extensions and it cannot be installed in the Visual Studio:

![image](https://user-images.githubusercontent.com/287778/206871539-91d95fe6-2239-4b89-8923-2025397df2e4.png)

```
10.12.2022 20:07:44 - Microsoft VSIX Installer
10.12.2022 20:07:44 - -------------------------------------------
10.12.2022 20:07:44 - vsixinstaller.exe version:
10.12.2022 20:07:44 - 17.4.2119
10.12.2022 20:07:44 - -------------------------------------------
10.12.2022 20:07:44 - Command line parameters:
10.12.2022 20:07:44 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,E:\Downloads\Microsoft.Sarif.Viewer.2019.vsix
10.12.2022 20:07:44 - -------------------------------------------
10.12.2022 20:07:44 - Microsoft VSIX Installer
10.12.2022 20:07:44 - -------------------------------------------
10.12.2022 20:07:45 - Initializing Install...
10.12.2022 20:07:45 - Extension Details...
10.12.2022 20:07:45 - 	Identifier         : Microsoft.Sarif.Viewer.Michael C. Fanning.f17e897a-fd38-4e1f-99db-19fa34a4e184
10.12.2022 20:07:45 - 	Name               : Microsoft SARIF Viewer
10.12.2022 20:07:45 - 	Author             : Microsoft DevLabs
10.12.2022 20:07:45 - 	Version            : 3.0.113.19151
10.12.2022 20:07:45 - 	Description        : Visual Studio Static Analysis Results Interchange Format (SARIF) log file viewer
10.12.2022 20:07:45 - 	Locale             : en-US
10.12.2022 20:07:45 - 	MoreInfoURL        : 
10.12.2022 20:07:45 - 	InstalledByMSI     : False
10.12.2022 20:07:45 - 	SupportedFrameworkVersionRange : [4.5,)
10.12.2022 20:07:45 - 
10.12.2022 20:07:46 - 	SignatureState     : ValidSignature
10.12.2022 20:07:46 - 	SignedBy           : Microsoft Corporation
10.12.2022 20:07:46 - 	Certificate Info   : 
10.12.2022 20:07:46 - 		-------------------------------------------------------
10.12.2022 20:07:46 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
10.12.2022 20:07:46 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
10.12.2022 20:07:46 - 		[Serial Number] : 33000004BAC9F395E14BCDB2180000000004BA
10.12.2022 20:07:46 - 		[Not Before]    : 7.6.2022 19:44:21
10.12.2022 20:07:46 - 		[Not After]     : 1.6.2023 19:44:21
10.12.2022 20:07:46 - 		[Thumbprint]    : D9106ACE5B2D7DEF4A6F2BB29C448DC370F84406
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - 	Supported Products : 
10.12.2022 20:07:46 - 		Microsoft.VisualStudio.Community
10.12.2022 20:07:46 - 			Version : [15.0,17.0)
10.12.2022 20:07:46 - 			ProductArchitecture : x86
10.12.2022 20:07:46 - 		Microsoft.VisualStudio.Enterprise
10.12.2022 20:07:46 - 			Version : [15.0,17.0)
10.12.2022 20:07:46 - 			ProductArchitecture : x86
10.12.2022 20:07:46 - 		Microsoft.VisualStudio.Pro
10.12.2022 20:07:46 - 			Version : [15.0,17.0)
10.12.2022 20:07:46 - 			ProductArchitecture : x86
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - 	References         : 
10.12.2022 20:07:46 - 		-------------------------------------------------------
10.12.2022 20:07:46 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
10.12.2022 20:07:46 - 		Name         : Visual Studio MPF 14.0
10.12.2022 20:07:46 - 		Version      : [14.0,15.0)
10.12.2022 20:07:46 - 		MoreInfoURL  : 
10.12.2022 20:07:46 - 		Nested       : No
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - 	Prerequisites      : 
10.12.2022 20:07:46 - 		-------------------------------------------------------
10.12.2022 20:07:46 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10.12.2022 20:07:46 - 		Name         : Visual Studio core editor
10.12.2022 20:07:46 - 		Version      : [15.0,17.0)
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - 		-------------------------------------------------------
10.12.2022 20:07:46 - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
10.12.2022 20:07:46 - 		Name         : C# and Visual Basic
10.12.2022 20:07:46 - 		Version      : [15.0,17.0)
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - Signature Details...
10.12.2022 20:07:46 - 	Extension is signed with a valid signature.
10.12.2022 20:07:46 - 
10.12.2022 20:07:46 - Searching for applicable products...
10.12.2022 20:07:46 - Found installed product - Global Location
10.12.2022 20:07:46 - Found installed product - Visual Studio Professional 2022
10.12.2022 20:07:46 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by NguyenBaTu1** [comment]
Only works on vs 2017, 2019. if you use 2022 then here it is
https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer2022
