### ISSUE TITLE
Looping exception related to Microsoft.Common.props not found

### ISSUE THREAD

**Issue by sandrock** [dotnet/upgrade-assistant#1410]
### Describe the bug

The assistant fails early because it does not find an obscure file. 

### To Reproduce

`upgrade-assistant.exe upgrade My.sln --non-interactive`

### Exceptions

> [18:11:58 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.101\
[18:11:58 INF] Using Visual Studio install from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise [v15]
[18:12:02 INF] Loading upgrade progress file at C:\xxx\.upgrade-assistant
[18:12:02 INF] Initializing upgrade step Back up project
[18:12:02 INF] Applying upgrade step Back up project
[18:12:02 INF] Backing up C:\xxx\project1 to C:\xxx.backup\xxx\project1
[18:12:02 INF] Project backed up to C:\xxx.backup\project1
[18:12:02 INF] Upgrade step Back up project applied successfully
[18:12:02 INF] Initializing upgrade step Convert project file to SDK style
[18:12:03 INF] Applying upgrade step Convert project file to SDK style
[18:12:03 INF] Converting project file format with try-convert, version 0.4.405701+c03504fd0b8fdcede2143f0e931d0d61b2dc29ff
[18:12:02 INF] Initializing upgrade step Convert project file to SDK style
[18:12:03 INF] Applying upgrade step Convert project file to SDK style
[18:12:03 INF] Converting project file format with try-convert, version 0.4.405701+c03504fd0b8fdcede2143f0e931d0d61b2dc29ff
[18:12:03 ERR] Unexpected error applying step
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Microsoft.Common.props" is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at MSBuild.Abstractions.UnconfiguredProject.LoadProjects(ProjectCollection collection, ProjectRootElement rootElement)
   at MSBuild.Abstractions.MSBuildConversionWorkspace.TryCreateSdkBaselineProject(String projectFilePath, IProject project, IProjectRootElement root, ImmutableDictionary`2 configurations, String tfm, Boolean keepCurrentTFMs, Nullable`1& baselineProject)
   at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertInProcessTool.RunAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.RunTryConvertAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.TryConvert.TryConvertRunner.ApplyAsync(IUpgradeContext context, IProject project, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178
Command (Apply next step (Convert project file to SDK style)) did not succeed
[18:12:03 INF] Applying upgrade step Convert project file to SDK style
[18:12:03 INF] Converting project file format with try-convert, version 0.4.405701+c03504fd0b8fdcede2143f0e931d0d61b2dc29ff
[18:12:04 ERR] Unexpected error applying step
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Microsoft.Common.props" is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
...
loops
...

### Analysis

It says 

> The imported project  
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Microsoft.Common.props"
   was not found.

And I do not have this path here. But this one exists:

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.props"

The csproj starts like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```

Not sure what's going on :(

### Further technical details

- Windows version 
  - Windows 10 pro x64 10.0.17763 N/A Build 17763
- Include the output of `dotnet --list-sdks`
  - 2.1.525 [C:\Program Files\dotnet\sdk]
  - 2.1.818 [C:\Program Files\dotnet\sdk]
  - 5.0.404 [C:\Program Files\dotnet\sdk]
  - 6.0.101 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`: 
  - 0.4.405701+c03504fd0b8fdcede2143f0e931d0d61b2dc29ff
- Include the log file `upgrade-assistant.clef` that is produced in the working directory
  - no. it's way too big, and I had to Ctrl+C the assistant, is was looping indefinitely.

**Comment by sandrock** [comment]
I found a workaround: 

I copied the other file at the expected location. 

Now the step succeeds.
