### ISSUE TITLE
assistant crashes at the end when handling the report

### ISSUE THREAD

**Issue by sandrock** [dotnet/upgrade-assistant#1411]
### Describe the bug

The assistant crashes at the end when handling the report. 

### To Reproduce

`upgrade-assistant.exe upgrade My.sln --non-interactive`

### Exceptions (if any)

> [18:54:16 INF] Applying upgrade step Finalize upgrade
[18:54:16 INF] Upgrade step Finalize upgrade applied successfully
[18:54:16 INF] Upgrade has completed. Please review any changes.
[18:54:16 INF] Deleting upgrade progress file at C:\xxx\.upgrade-assistant
[18:54:16 ERR] Unexpected error
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.DotNet.UpgradeAssistant.Analysis.SarifAnalyzeResultWriter.ExtractResults(IList`1 analyzeResults) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Analysis/SarifAnalyzeResultWriter.cs:line 103
   at Microsoft.DotNet.UpgradeAssistant.Analysis.SarifAnalyzeResultWriter.ExtractRunsAsync(IAsyncEnumerable`1 analyzeResultDefinitions)+MoveNext() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Analysis/SarifAnalyzeResultWriter.cs:line 57
   at Microsoft.DotNet.UpgradeAssistant.Analysis.SarifAnalyzeResultWriter.ExtractRunsAsync(IAsyncEnumerable`1 analyzeResultDefinitions)+MoveNext() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Analysis/SarifAnalyzeResultWriter.cs:line 54
   at Microsoft.DotNet.UpgradeAssistant.Analysis.SarifAnalyzeResultWriter.ExtractRunsAsync(IAsyncEnumerable`1 analyzeResultDefinitions)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Microsoft.DotNet.UpgradeAssistant.Analysis.SarifAnalyzeResultWriter.WriteAsync(IAsyncEnumerable`1 results, Stream stream, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.Analysis/SarifAnalyzeResultWriter.cs:line 41
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.WriteUpgradeReport(IOutputResultWriter resultWriter, IUpgradeContext context, CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 109
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Commands/Upgrade/ConsoleUpgrade.cs:line 94
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 60

### Further technical details

- Windows version 
  - Windows 10 pro x64 10.0.17763 N/A Build 17763
- Include the output of `dotnet --list-sdks`
  - 2.1.525 [C:\Program Files\dotnet\sdk]
  - 2.1.818 [C:\Program Files\dotnet\sdk]
  - 5.0.404 [C:\Program Files\dotnet\sdk]
  - 6.0.101 [C:\Program Files\dotnet\sdk]
  - 7.0.102 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`: 
  - 0.4.405701+c03504fd0b8fdcede2143f0e931d0d61b2dc29ff
- Include the log file `upgrade-assistant.clef` that is produced in the working directory
  - no.

**Comment by ambalesunny87** [comment]
I am facing the same issue when upgrading my project. BTW I am not seeing any upgrade-assistant.clef  produced and finally it creates the upgrade report file, but its empty always.

Any update on this issue?

**Comment by ambalesunny87** [comment]
Current upgrade assistant version installed : 0.4.421302+be0ea11e8234f2a0bde2d170b0fdd455fa4f9a45
Windows OS : Windows 10 Enterprise (19044.3086)
No log file generated by the name upgrade-assistant.clef

**Comment by ambalesunny87** [comment]
How did it get resolved @sandrock
