### ISSUE TITLE
Upgrade Error I don't understand

### ISSUE THREAD

**Issue by pault3ch** [dotnet/upgrade-assistant#1422]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

the project is 5.x and analyzer runs without problem.

[01:22:42 INF] Initializing upgrade step Select project to upgrade
[01:22:42 ERR] Support for upgrading to .NET MAUI Upgrade is limited to Xamarin.Forms version 4.8 or higher. To learn more please read: https://aka.ms/upgradeassistant/maui/requirements
[01:22:42 ERR] Unexpected error initializing step
System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(IFormatProvider provider, String format, Object arg0, Object arg1)
   at System.SR.Format(String str, Object arg0, Object arg1) in /_/shared/Common/SR.cs:line 11
   at Microsoft.DotNet.UpgradeAssistant.Extensions.Maui.XamarinFormsVersionCheck.get_UpgradeMessage() in /_/src/extensions/maui/Microsoft.DotNet.UpgradeAssistant.Extensions.Maui/XamarinFormsVersionCheck.cs:line 33
   at Microsoft.DotNet.UpgradeAssistant.Steps.Solution.CurrentProjectSelectionStep.RunChecksAsync(IProject project, CancellationToken token) in /_/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Solution/CurrentProjectSelectionStep.cs:line 227
   at Microsoft.DotNet.UpgradeAssistant.Steps.Solution.CurrentProjectSelectionStep.<>c__DisplayClass19_0.<<InitializeImplAsync>b__2>d.MoveNext() in /_/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Solution/CurrentProjectSelectionStep.cs:line 99
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIteratorWithTask`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs:line 372
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<AllAsync>g__Core|207_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/All.cs:line 34
   at System.Linq.AsyncEnumerable.<AllAsync>g__Core|207_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/All.cs:line 34
   at Microsoft.DotNet.UpgradeAssistant.Steps.Solution.CurrentProjectSelectionStep.InitializeImplAsync(IUpgradeContext context, CancellationToken token) in /_/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Solution/CurrentProjectSelectionStep.cs:line 98
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.InitializeAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 134

**Comment by jstedfast** [comment]
I think this is likely fixed by https://github.com/dotnet/upgrade-assistant/pull/1418

**Comment by pault3ch** [comment]
hmm I followed the steps to get latest do I need some preview version of upgrade assistant to get fixes from 2 weeks ago ?
https://dotnet.microsoft.com/en-us/platform/upgrade-assistant I did this, installed .net 6 and 7 SDK. Xamarin forms is 5.x.
Only thing that might help and it has really frustrated me is I have the android xamarin project csproj and also a shproj for the shared c#, not sure if it's supported. I can output the analyzer results if that will help they run without error

**Comment by pault3ch** [comment]
here's my version >upgrade-assistant --version
0.4.410601+6304b1d0784e32e20ef0299db22bc9e3f6a9b3f3

**Comment by pault3ch** [comment]
maybe this would help 
![image](https://user-images.githubusercontent.com/68454484/220955816-8ca759a4-dca7-4bc5-99e1-bfd69689e3f0.png)

**Comment by jstedfast** [comment]
That fix was started 2 weeks ago but was just merged yesterday and there has not yet been a release with it.

My comment was mostly a note to us to check the relation and verify that this is the same issue.

Sorry for any confusion!

**Comment by AdamDiament** [comment]
I have the same issue. When will the new version be released please? My upgrade assistant is 0.4.410601

**Comment by mgoertz-msft** [comment]
No longer applicable.
