### ISSUE TITLE
Exception when processing an relative path for an Import directive for a projitems file

### ISSUE THREAD

**Issue by ycholette** [dotnet/upgrade-assistant#1504]
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory
This file ain't generated on my pc, but the exception is the very first thing that gets output after `Starting upgrade of selected nodes for...`  

### Describe the bug
My csproj contains this line 
`<Import Project="..\Shared\Shared.projitems" Label="Shared" />`  
and the tool outputs an exception (see exception section).  
  
The tool is ran in the root directory where the solution is located, but projects are in sub directories, so the tool is invoke like this:  
  
`upgrade-assistant upgrade ProjectFolder\ProjectFolder.csproj`   
  
The projitems is located at `Shared/Shared.projitems`

### To Reproduce
Run the tool like this `upgrade-assistant upgrade ProjectFolder\ProjectFolder.csproj`  and have an import directive with a relative path.

### Exceptions (if any)
```
> Microsoft.UpgradeAssistant.Transformers.ProjectSdkStyleTransformer
>         info: Converting project '(project file redacted).csproj' to SDK style.
>         error: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project
> "C:\Users\(username redacted)\AppData\Local\Temp\UpgradeAssistant\Projects\088CA948-6AB7-4511-A774-2900C1AABD3A\Shared\Shared.projitems" was not found. Confirm that the expression in the
> Import declaration "..\Shared\Shared.projitems" is correct, and that the file exists on disk.
> C:\Users\(username redacted)\AppData\Local\Temp\UpgradeAssistant\Projects\088CA948-6AB7-4511-A774-2900C1AABD3A\2023-07-24--15-43-02\VS2022.csproj
>    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
>    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String
> unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement,
> List`1& projects, SdkResult& sdkResult)
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
>    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
>    at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
>    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
>    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount,
> PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase
> projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean
> interactive)
>    at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext
> evaluationContext)
>    at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext
> evaluationContext)
>    at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings,
> EvaluationContext evaluationContext, Boolean interactive)
>    at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection
> projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, Boolean interactive)
>    at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
>    at MSBuild.Abstractions.UnconfiguredProject.LoadProjects(ProjectCollection collection, ImmutableDictionary`2 globalProperties, String projectFilePath) in
> D:\a\_work\1\s\src\Experiments\UpgradeAssistant\msbuild\Abstractions\UnconfiguredProject.cs:line 31
>    at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb, String
> actualProjectPath) in D:\a\_work\1\s\src\Experiments\UpgradeAssistant\msbuild\Abstractions\MSBuildConversionWorkspace.cs:line 57
>    at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb, String
> actualProjectPath) in D:\a\_work\1\s\src\Experiments\UpgradeAssistant\msbuild\Abstractions\MSBuildConversionWorkspaceLoader.cs:line 45
>    at Microsoft.UpgradeAssistant.TryConvert.Slices.Services.TryConvertService.ConvertAsync(OperationContext context, String projectFilePath, TargetFramework targetFramework,
> ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Experiments\UpgradeAssistant\msbuild\Slices\Services\TryConvertService.cs:line 39
```

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)  
`Version	10.0.19045 Build 19045 64 bits`

- Include the output of `dotnet --list-sdks`  
```
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
```

- Include the output of `upgrade-assistant --version`
`0.5.30.21767`

**Comment by Nageena** [comment]
Any updates on the issue. I am facing exact same issue for my referenced shared project.

**Comment by agr** [comment]
Same happens in 0.5.261.51392

**Comment by slidonnici** [comment]
I also have the same issue, but I don't have any <Import Project>, just some <Reference Include> with relative path in the <HintPath> tag.

**Comment by ericnewton76** [comment]
This also happens if you have a node like:

```xml
<ItemGroup>
    <None Include="NLog.config" />
</ItemGroup>
```

and the NLog.config file is missing.
