### ISSUE TITLE
Unable to run Upgrade assistant latest version 0.5.261 through automated pipeline

### ISSUE THREAD

**Issue by niteshcse009** [dotnet/upgrade-assistant#1518]
Unable to run Upgrade assistant latest version 0.5.261 through automated pipeline, it's failing with below error message 

Initializing and loading extensions...
Telemetry

Upgrade Assistant collects usage data in order to help us improve your 
experience. The data is collected by Microsoft and shared with the community. 
You can opt-out of telemetry by setting the 
DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT environment variable to '1' or 'true' 
using your favorite shell.

Read more about Upgrade Assistant telemetry: 
https://aka.ms/upgrade-assistant-telemetry
Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

Press any key to continue...
System.InvalidOperationException: Cannot read keys when either application does 
not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at 
Microsoft.UpgradeAssistant.Cli.Startup.FirstUseStartup.StartupAsync(Cancellation
Token cancellationToken) in 
D:\a\_work\1\s\src\Experiments\UpgradeAssistant\cli\Startup\FirstUseStartup.cs:l
ine 37

I have also tried setting environment variable as suggested in logs but still failing with same message.

**Comment by abpiskunov** [comment]
@niteshcse009  did you set DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT=1 or true? It does work on our CI machine with "true". There seem to be a bug when value is 1. Please try to set value to "true" to get unblocked while issue is being fixed.

**Comment by abpiskunov** [comment]
Also DOTNET_UPGRADEASSISTANT_SKIP_FIRST_TIME_EXPERIENCE is the correct variable to avoid this message to appear in the console. DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT is the variable to opt out from telemetry when upgrade is actually running.

**Comment by niteshcse009** [comment]
Hi Anton,

I have tried both way 1 and true but it still doesn't work.

Regards, Nitesh

**Comment by abpiskunov** [comment]
Just to clarify: you set DOTNET_UPGRADEASSISTANT_SKIP_FIRST_TIME_EXPERIENCE=true ?

**Comment by janbalcarik** [comment]
Good day,

I also tested all possible settings using set as 1 and true. But always the same result. We need the result in the file.

Example:
upgrade-assistant upgrade -o sdkstyle --non-interactive c:\test\test.csproj > test.txt

output:
Initializing and loading extensions...
Determining supported upgrades...
System.IO.IOException: Neplatný popisovaƒ.
   at System.ConsolePal.Clear()
   at Spectre.Console.Flow.FlowRunner.RunAsync(CancellationToken cancellationToken) in 
D:\a\_work\1\s\src\Experiments\UpgradeAssistant\spectre.flow\Flow\FlowRunner.cs:line 96

Version:
C:\>upgrade-assistant -v
0.5.261.51392

**Comment by abpiskunov** [comment]
@janbalcarik this is different issue and thanks for pointing it out. We are working on the fix for this for the next release. Original issue was about opting out from telemetry and first time question via env variables and it does work for us (we have our tests using them for every build).

**Comment by abpiskunov** [comment]
We have integration tests setting environment variables like below running every day on CI machines. Could you please double check that you do have them set? Print out all variables?         EnvironmentVariables["DOTNET_UPGRADEASSISTANT_SKIP_FIRST_TIME_EXPERIENCE"] = "true";
        EnvironmentVariables["DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT"] = "true";

**Comment by CCostaT** [comment]
I just tried this way and aparrently it works:

![image](https://github.com/dotnet/upgrade-assistant/assets/48755988/c49e882c-d83a-4804-8df3-25a640a0d5fa)

No errors so far
