### ISSUE TITLE
NuGet floating version failing with NuGet.Versioning.NuGetVersion.Parse

### ISSUE THREAD

**Issue by Herve-M** [dotnet/upgrade-assistant#1542]
### Describe the bug
.NET SDK style project using PackageReference with floating version fail during upgrade. 

### To Reproduce
``` xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.*" />
  </ItemGroup>
</Project>
```

Then: `upgrade-assistant upgrade worker.csproj -f net8.0 --operation Inplace --non-interactive`

### Exceptions (if any)
```
reference.package Microsoft.Extensions.Hosting 6.0.*...
        Microsoft.UpgradeAssistant.Transformers.DefaultPackageMapTransformer
        info: Removing package 'Microsoft.Extensions.Hosting' from project '\source\repos\demo\worker.csproj'.
        error: System.ArgumentException: '6.0.*' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at Microsoft.UpgradeAssistant.NuGet.NuGetClient.CompareVersions(String left, String right) in
D:\a\_work\1\s\src\nuget\NuGetClient.cs:line 62
   at Microsoft.UpgradeAssistant.Cli.Slices.Services.NuGet.NuGetService.CompareVersions(String left, String right) in
D:\a\_work\1\s\src\cli\Slices\Services\NuGet\NuGetService.cs:line 34
   at Microsoft.UpgradeAssistant.Services.ProjectExtensions.<>c__DisplayClass0_0.<AddPackage>b__0(Package x) in
D:\a\_work\1\s\src\engine\Services\Project\ProjectExtensions.cs:line 22
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.UpgradeAssistant.Services.ProjectExtensions.AddPackage(IProject project, OperationContext context, String packageName,
String version, ILogger logger, Boolean preserveLatestVersion) in D:\a\_work\1\s\src\engine\Services\Project\ProjectExtensions.cs:line 21
   at Microsoft.UpgradeAssistant.Transformers.PackageMapTransformerBase.RunAsync(OperationContext context, SliceNode node,
CancellationToken cancellationToken) in D:\a\_work\1\s\src\engine\Transformers\Package\PackageMapTransformerBase.cs:line 83
   at Microsoft.UpgradeAssistant.Operations.Operation.RunTransformerAsync(OperationContext context, SliceNode node, Lazy`2 transformer,
TelemetryEvent telemetryEvent, OperationLogger transformerLogger, CancellationToken cancellationToken) in
D:\a\_work\1\s\src\engine\Operations\Operation.cs:line 386
   at Microsoft.UpgradeAssistant.Operations.Operation.RunNodeTransformersAsync(OperationContext context, SliceNode node, SliceNodeStats
nodeStats, CancellationToken cancellationToken) in D:\a\_work\1\s\src\engine\Operations\Operation.cs:line 274
        info: Done
        Microsoft.UpgradeAssistant.Transformers.InplacePackageReferenceTransformer
        info: Done
Failed
```

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
- Include the output of `dotnet --list-sdks`
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.825c015e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.825c015e
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.418 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]
```
- Include the output of `upgrade-assistant --version`: `0.5.568.12974`

**Comment by abpiskunov** [comment]
Fixed in latest versions.

**Comment by sbest-gcm** [comment]
> Fixed in latest versions.

No it's not.
