### ISSUE TITLE
Error running tool from project location

### ISSUE THREAD

**Issue by lunchin** [dotnet/upgrade-assistant#246]
Steps to reproduce:

1. Install latest `upgrade-assistant` version as a .NET CLI tool how described in[README.md
2. Try running the tool from any folder except its installation location, for example from "D:\projects\MyProject" folder

```
PS D:\projects\MyProject> upgrade-assistant .\MyProject.sln
```

**Expected**: the tool works and starts analyzing the solution.

**Actual**: the tool crashes with exception:

```
-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.211942+c8effffd96b96d68652b6ef3dc3f01c5983ef66b -
-----------------------------------------------------------------------------------------

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'D:\projects\MyProject\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.dll'. The system cannot find the file specified.
File name: 'D:\projects\MyProject\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.DotNet.UpgradeAssistant.Extensions.ExtensionProviderExtensions.RegisterExtensionServices(IServiceCollection services, IConfiguration configuration) in /_/src/extensions/Microsoft.DotNet.UpgradeAssistant.Extensions/ExtensionProviderExtensions.cs:line 92
   at Microsoft.DotNet.UpgradeAssistant.Extensions.ExtensionProviderExtensions.AddExtensions(IServiceCollection services, IConfiguration configuration, IEnumerable`1 additionalExtensionPaths) in /_/src/extensions/Microsoft.DotNet.UpgradeAssistant.Extensions/ExtensionProviderExtensions.cs:line 44
   at Microsoft.DotNet.UpgradeAssistant.Cli.Program.<>c__DisplayClass4_0.<RunCommandAsync>b__0(HostBuilderContext context, IServiceCollection services) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Program.cs:line 100
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, Action`1 configureOptions, CancellationToken cancellationToken)
   at Microsoft.DotNet.UpgradeAssistant.Cli.Program.RunCommandAsync(MigrateOptions options, Action`2 serviceConfiguration, AppCommand appCommand, CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Program.cs:line 78
   at Microsoft.DotNet.UpgradeAssistant.Cli.Program.RunMigrationAsync(MigrateOptions options) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/Program.cs:line 60
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Note: absolute path to "sln" or "csproj" file doesn't work too - same error.

**Workaround**: go to `upgrade-assistant` installation location and run it from there:

```
PS C:\Users\pavel.nezhencev\.dotnet\tools\.store\upgrade-assistant\0.2.211942\upgrade-assistant\0.2.211942\tools\net5.0\any> upgrade-assistant D:\projects\MyProject\MyProject.sln
```

**Sample result**:

```
-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.211942+c8effffd96b96d68652b6ef3dc3f01c5983ef66b -
-----------------------------------------------------------------------------------------

[21:33:37 INF] Configuration loaded from context base directory: C:\Users\pavel.nezhencev\.dotnet\tools\.store\upgrade-assistant\0.2.211942\upgrade-assistant\0.2.211942\tools\net5.0\any\
[21:33:38 INF] MSBuild registered from C:\Program Files\dotnet\sdk\5.0.103\
[21:33:38 INF] Registered 1 extensions:
        Default extension
[21:33:38 INF] Loading migration progress file at D:\projects\MyProject\.upgrade-assistant
[21:33:38 INF] Initializing migration step Select an entrypoint

Migration Steps

1. [Next step] Select an entrypoint

Choose a command:
   1. Apply next step (Select an entrypoint)
   2. Skip next step (Select an entrypoint)
   3. See more step details
   4. Configure logging
   5. Exit
>
```

**Comment by mjrousos** [comment]
Thanks for the report, @lunchin. I believe this issue is already fixed in the latest builds of upgrade-assistant. Try `dotnet tool update -g upgrade-assistant` (you should get version 0.2.212406 or higher) and let me know if the issue still repros.
