### ISSUE TITLE
Exception: [Failed] Update TFM : Sequence contains no matching element

### ISSUE THREAD

**Issue by iwhp** [dotnet/upgrade-assistant#319]
During step 3 (Update TFM) we get the following exception:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.get_TFM() in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.cs:line 258
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildTargetTFMSelector.SelectTFM(IProject project) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildTargetTFMSelector.cs:line 73
   at Microsoft.DotNet.UpgradeAssistant.Steps.ProjectFormat.SetTFMStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token) in /_/src/steps/Microsoft.DotNet.UpgradeAssistant.Steps.ProjectFormat/SetTFMStep.cs:line 44
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 169

```
Here is our .csconfig

```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\packages\EntityFramework.6.4.4\build\EntityFramework.props" Condition="Exists('..\..\packages\EntityFramework.6.4.4\build\EntityFramework.props')" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <ManifestCertificateThumbprint>C850F9C181AA6227CFA85566F6EEED598508C90F</ManifestCertificateThumbprint>
    <ManifestKeyFile>signing.pfx</ManifestKeyFile>
    <GenerateManifests>true</GenerateManifests>
    <SignManifests>true</SignManifests>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <ApplicationIcon>Resources\view-calendar-time-spent.ico</ApplicationIcon>
    <DelaySign>true</DelaySign>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <PublishUrl>\\dfs\Pool\Setup\Ardimedia.Com\Ardimedia.Com.Erp\Test\ClickOnce\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Unc</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ProductName>Ardimedia.Com.Erp</ProductName>
    <PublisherName>Ardimedia</PublisherName>
    <CreateWebPageOnPublish>true</CreateWebPageOnPublish>
    <WebPage>default.htm</WebPage>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>38</ApplicationRevision>
    <ApplicationVersion>3.1.1.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <CreateDesktopShortcut>true</CreateDesktopShortcut>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CodeAnalysisRules></CodeAnalysisRules>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisIgnoreGeneratedCode>false</CodeAnalysisIgnoreGeneratedCode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>LocalIntranet</TargetZone>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Accessibility" />
    <Reference Include="System.configuration" />
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data.OracleClient" />
    <Reference Include="System.Design" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Net" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Transactions" />
    <Reference Include="Telerik.WinControls.ChartView, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.ChartView.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.PdfViewer, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.PdfViewer.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.PivotGrid, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.PivotGrid.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadChart, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadChart.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadDiagram, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadDiagram.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadDock, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadDock.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadMap, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadMap.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadMarkupEditor, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadMarkupEditor.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadSpreadsheet, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadSpreadsheet.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RadWebCam, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RadWebCam.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.WinControls.RichTextEditor, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5bb2a467cbec794e, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.WinControls.RichTextEditor.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Core, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Documents.Core.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Fixed, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Documents.Fixed.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Spreadsheet, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Documents.Spreadsheet.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Documents.Spreadsheet.FormatProviders.OpenXml.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Spreadsheet.FormatProviders.Pdf, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Documents.Spreadsheet.FormatProviders.Pdf.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Zip, Version=2020.3.915.40, Culture=neutral, PublicKeyToken=5803cfa389c90ce7, processorArchitecture=MSIL">
      <HintPath>..\..\lib\RCWF\2020.3.915.40\Telerik.Windows.Zip.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\Aip\AipDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Aip\AipListDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\AipStatus\AipStatusDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ControlTabs\AipTabView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\AipType\AipTypeDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\AipType\AipTypeView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Aip\AipView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\AipStatus\AipStatusView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ControlTabs\OrderTabView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkOrderView\OrderDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkOrderView\OrderList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkOrderView\OrderView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Customer\CustomerView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ControlTabs\EmployeeTabView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Employee\EmployeeView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ControlTabs\ProductTabView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Product\ProductView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Timeslip\TimeslipProductSummary.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkCategory\WorkCategoryDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkCategory\WorkCategoryList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Employee\EmployeeDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Employee\EmployeeList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Product\ProductDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Product\ProductList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\Timeslip\TimeslipDetails.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ControlTabs\WorkCategoryTabView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\WorkCategory\WorkCategoryView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Infrastructure\DsErpCrud.cs">
      <DependentUpon>DsErpCrud.xsd</DependentUpon>
    </Compile>
    <Compile Update="Infrastructure\DsErpList.cs">
      <DependentUpon>DsErpList.xsd</DependentUpon>
    </Compile>
    <Compile Update="Controls\OutlookBar\BaseStackStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\NavMasterData.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\NavSystem.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\NavView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\HeaderStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\LeftSpine.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\OutlookBar\StackStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <EmbeddedResource Include="Properties\licenses.licx" />
    <None Include="Ardimedia.Com.Erp.Ui.Win_TemporaryKey.pfx" />
    <None Update="Infrastructure\DsErpCrud.xsc">
      <DependentUpon>DsErpCrud.xsd</DependentUpon>
    </None>
    <None Update="Infrastructure\DsErpCrud.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsErpCrud1.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </None>
    <None Update="Infrastructure\DsErpCrud.xss">
      <DependentUpon>DsErpCrud.xsd</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <None Update="Infrastructure\DsErpList.xsc">
      <DependentUpon>DsErpList.xsd</DependentUpon>
    </None>
    <None Update="Infrastructure\DsErpList.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <SubType>Designer</SubType>
      <LastGenOutput>DsErpList.Designer.cs</LastGenOutput>
    </None>
    <None Update="Infrastructure\DsErpList.xss">
      <DependentUpon>DsErpList.xsd</DependentUpon>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Content Include="Resources\Ardimedia.Com.Erp.adp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Folder.bmp" />
    <Resource Include="Resources\Folder24.bmp" />
    <Content Include="Resources\Ardimedia.Com.ErpOld.adp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\view-calendar-time-spent.ico" />
    <Resource Include="Resources\Calendar.ico" />
    <Resource Include="Resources\t227.ico" />
    <Resource Include="Resources\Calendar52Day.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Amx.Amms.Domain\Amx.Amms.Domain.csproj" />
    <ProjectReference Include="..\..\Amx.Amms.Infrastructure\Amx.Amms.Infrastructure.csproj" />
    <ProjectReference Include="..\Ardimedia.Com.Erp\Ardimedia.Com.Erp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="System.Runtime.Caching" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Am.BaseSystem" Version="2.0.0-20210301-01" />
    <PackageReference Include="Am.Domain" Version="2.0.0-20210301-01" />
    <PackageReference Include="Am.Infrastructure" Version="2.0.0-20210301-01" />
    <PackageReference Include="Am.Practices.Amms" Version="1.6.0-CI-20180618-130639" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.1" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="3.1.8" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="Microsoft.Win32.Registry.AccessControl" Version="5.0.0" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="5.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.CodeDom" Version="5.0.0" />
    <PackageReference Include="System.Collections.Immutable" Version="1.7.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="5.0.0" />
    <PackageReference Include="System.Composition" Version="5.0.0" />
    <PackageReference Include="System.Composition.AttributedModel" Version="5.0.0" />
    <PackageReference Include="System.Composition.Convention" Version="5.0.0" />
    <PackageReference Include="System.Composition.Hosting" Version="5.0.0" />
    <PackageReference Include="System.Composition.Runtime" Version="5.0.0" />
    <PackageReference Include="System.Composition.TypedParts" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Data.Odbc" Version="5.0.0" />
    <PackageReference Include="System.Data.OleDb" Version="5.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.7.1" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="5.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="5.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.0" />
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.IO.Packaging" Version="5.0.0" />
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.IO.Ports" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.4" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    <PackageReference Include="System.Reflection.Emit.ILGeneration" Version="4.7.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Runtime.Caching" Version="5.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="5.0.0" />
    <PackageReference Include="System.Security.Permissions" Version="5.0.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="5.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="5.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="5.0.0" />
    <PackageReference Include="System.Threading.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="UI.for.WinForms.Common" Version="2020.3.1020" />
    <PackageReference Include="UI.for.WinForms.GridView" Version="2020.3.1020" />
    <PackageReference Include="UI.for.WinForms.Scheduler" Version="2020.3.1020" />
    <PackageReference Include="UI.for.WinForms.Themes" Version="2020.3.1020" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties ShouldAddDPIScalingManifest="False" />
    </VisualStudio>
  </ProjectExtensions>
  <Import Project="..\..\packages\EntityFramework.6.4.4\build\EntityFramework.targets" Condition="Exists('..\..\packages\EntityFramework.6.4.4\build\EntityFramework.targets')" />
</Project>

```

**Comment by mjrousos** [comment]
Thanks, @iwhp. I'll take a look.

**Comment by caveman-dick** [comment]
I had this error. It was because I had already manually converted some libraries over to the SDK format and marked them with multiple TargetFrameworks which the tool does not support:

https://github.com/dotnet/upgrade-assistant/blob/main/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.cs#L206

I took off the extra frameworks and then re-run the tool and it worked.

**Comment by sunandabalu** [comment]
This should be fixed in this version - https://www.nuget.org/packages/upgrade-assistant/0.2.220602. Closing.
