### ISSUE TITLE
Mismatched project.assets.json (from the converted project) breaks the tool

### ISSUE THREAD

**Issue by oteinone** [dotnet/upgrade-assistant#436]
### Describe the bug
I was testing the tool on a .NET 4.7.2 class library project. The conversion tool was completed succesfully but I ran `git checkout -f` to undo the changes. Later I re-ran the tool and got the attached error. After deleting the bin/obj folders I could re-run the tool succesfully.

It seems that packages.config with .NET Framework 4.7.2 references and the lockfile with .NET 5 references caused this problem.

### To Reproduce
1. Run the upgrade-assistant on a project
2. Build the project
3. Undo changes (but keep obj folder)
4. Run upgrade-assistant again

### Exceptions (if any)

```
1. [Next step] Back up project
2. Convert project file to SDK style
3. Clean up NuGet package references
4. Update TFM
5. Update NuGet Packages
6. Add template files
7. Upgrade app config files
    a. Convert Application Settings
    b. Disable unsupported configuration sections
[21:37:02 INF] Saving upgrade progress file at C:\users\otto\source\repos\Suite_Temp\Source\Medixine.Base\.upgrade-assistant
[21:37:02 ERR] Unexpected error during upgrade.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetAllDependencies(TargetFrameworkMoniker tfm) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 158
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.ContainsDependency(TargetFrameworkMoniker tfm, Func`2 filter) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 140
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass64_0.<IsTransitivelyAvailable>b__0(TargetFrameworkMoniker tfm) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 99
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.IsTransitivelyAvailable(String packageName) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 99
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.<>c__DisplayClass2_0.<GetGeneralProjectComponentsAsync>b__1(String package) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\ComponentIdentifier.cs:line 92
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetGeneralProjectComponentsAsync(IProject project, IProjectFile file, CancellationToken token) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\ComponentIdentifier.cs:line 92
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetComponentsAsync(IProject project, CancellationToken token) in C:\Users\otto\upgrade-assistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\ComponentIdentifier.cs:line 25
   at Microsoft.DotNet.UpgradeAssistant.ProjectExtensions.AppliesToProjectAsync(Type type, IProject project, CancellationToken token) in C:\Users\otto\upgrade-assistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\ProjectExtensions.cs:line 60
   at Microsoft.DotNet.UpgradeAssistant.Steps.Configuration.ConfigUpdaterSubStep.IsApplicableImplAsync(IUpgradeContext context, CancellationToken token) in C:\Users\otto\upgrade-assistant\src\steps\Microsoft.DotNet.UpgradeAssistant.Steps.Configuration\ConfigUpdaterSubStep.cs:line 40
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.IsApplicableAsync(IUpgradeContext context, CancellationToken token) in C:\Users\otto\upgrade-assistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\UpgradeStep.cs:line 212
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.<>c__DisplayClass9_0.<<ShowUpgradeStepsAsync>b__0>d.MoveNext() in C:\Users\otto\upgrade-assistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleUpgrade.cs:line 134
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIteratorWithTask`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:line 277
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in C:\Users\otto\upgrade-assistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleUpgrade.cs:line 134
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in C:\Users\otto\upgrade-assistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleUpgrade.cs:line 134
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in C:\Users\otto\upgrade-assistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleUpgrade.cs:line 148
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in C:\Users\otto\upgrade-assistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleUpgrade.cs:line 134
```

### Further technical details
- Same problem was repeated with 0.2.220602, 0.2.221301 and locally built version

**Comment by sunandabalu** [comment]
@oteinone Is there a reason why you needed to undo the changes? Did you run into other issues while running upgrade-assistant to do that?

We can look into hardening the nuget package restore so we do not hit this issue.

**Comment by oteinone** [comment]
The reason why I did undo my changes was that I was evaluating the tool and trying to find the pain points in our conversion so that I could evaluate the time required for the changes. I was never going to go through with the whole conversion at this time. I think that for bigger projects this is a pretty common use case. Just getting a descriptive error advising to clean out bin/obj folders or something similar would have been good enough. Now I had to debug through the source code to find out how to recover from the situation.

Another issue I ran into - and you maybe have already thought of - was that there were some commonly used nuget libraries that would have supported .net5 in a newer version but they were not automatically upgraded. At least FluentValidation and maybe also AutoMapper. I can understand why this is not a trivial matter but I think a great feature would be to have the option to update nugets e.g. from [the most popular packages list](https://www.nuget.org/stats/packages) to the latest version or the first version supporting .net5. Even if there are breaking changes this would have a lot of potential to save time.

**Comment by mjrousos** [comment]
Thanks for the feedback, @oteinone. Upgrade Assistant should upgrade NuGet package references to newer versions if the newer versions support the chosen TFM and the current version doesn't. If this isn't working for some packages (you mentioned Automapper and FluentValidation), can you open a new issue so we can investigate and get that fixed?

**Comment by oteinone** [comment]
Definitely. I'll verify this and open tickets if I can still reproduce the
issues.

**Comment by twsouthwick** [comment]
A couple ideas:

- Check timestamp of lock file
- Rethrow linq error to identify callstacks where it is not available
