### ISSUE TITLE
Error during try-convert step

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#454]
### Describe the bug
Step 2. [Failed] Convert project file to SDK style
Unexpected error during upgrade.
System.InvalidOperationException: Sequence contains no matching element

### To Reproduce
1. Create a net48 class library project
2. Add an ApiController
3. Run upgrade assistant on the project

### Exceptions (if any)
[15:23:14 INF] Saving upgrade progress file at D:\...\.upgrade-assistant
[15:23:14 ERR] Unexpected error during upgrade.
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetAllDependencies(TargetFrameworkMoniker tfm) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 158
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.ContainsDependency(TargetFrameworkMoniker tfm, Func`2 filter) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 140
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass64_0.<IsTransitivelyAvailable>b__0(TargetFrameworkMoniker tfm) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 99
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.IsTransitivelyAvailable(String packageName) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 99
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.<>c__DisplayClass2_0.<GetGeneralProjectComponentsAsync>b__1(String package) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/ComponentIdentifier.cs:line 92
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetGeneralProjectComponentsAsync(IProject project, IProjectFile file, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/ComponentIdentifier.cs:line 92
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.ComponentIdentifier.GetComponentsAsync(IProject project, CancellationToken token) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/ComponentIdentifier.cs:line 25
   at Microsoft.DotNet.UpgradeAssistant.ProjectExtensions.AppliesToProjectAsync(Type type, IProject project, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/ProjectExtensions.cs:line 60
   at Microsoft.DotNet.UpgradeAssistant.Steps.Configuration.ConfigUpdaterSubStep.IsApplicableImplAsync(IUpgradeContext context, CancellationToken token) in /_/src/steps/Microsoft.DotNet.UpgradeAssistant.Steps.Configuration/ConfigUpdaterSubStep.cs:line 40
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.IsApplicableAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 212
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.<>c__DisplayClass9_0.<<ShowUpgradeStepsAsync>b__0>d.MoveNext() in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 134
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIteratorWithTask`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:line 277
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 134
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 134
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 148
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.ShowUpgradeStepsAsync(IEnumerable`1 steps, IUpgradeContext context, CancellationToken token, UpgradeStep currentStep, Int32 offset) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 134
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 59
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleUpgrade.cs:line 94
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.RunCommandAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 86
   at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in /_/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/ConsoleRunner.cs:line 44
```

### Further technical details
- Include the output of `upgrade-assistant --version`
version '0.2.222101'

**Comment by kylewhittington** [comment]
Same issue here -- did you manage to fix @sunandabalu?

**Comment by kylewhittington** [comment]
Actually, just figured out a fix for this ... delete the bin and obj folders in the project and it then works.

**Comment by mjrousos** [comment]
Yes, we should fix this so that it doesn't happen but the workaround for now is to delete the obj folder.

**Comment by haefele** [comment]
In my case this sadly doesn't work, they bin and obj-folders get re-created automatically, and then I run into the *Sequence contains no matching element* exception from this issue. 

Any other suggestions or workaround?

**Comment by sunandabalu** [comment]
@twsouthwick taking a look along with #436

**Comment by twsouthwick** [comment]
This is a duplicate with #436
