### ISSUE TITLE
`System.InvalidOperationException Package references from a lock file should always have a specific version`

### ISSUE THREAD

**Issue by valdisiljuconoks** [dotnet/upgrade-assistant#516]
### Describe the bug
After running tool against net472 targeted class library `System.InvalidOperationException` is thrown at 3rd step - "3. Clean up NuGet package references".

### To Reproduce
Attaching log.txt file.
[log-copy.txt](https://github.com/dotnet/upgrade-assistant/files/6459994/log-copy.txt)

### Exceptions (if any)
```
2021-05-11 17:25:42.493 +03:00 [FTL] Unexpected exception analyzing package references for: C:\Projects\MyProject.csproj
System.InvalidOperationException: Package references from a lock file should always have a specific version
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.ReferenceSatisfiesDependency(PackageDependency dependency, NuGetReference packageReference, Boolean minVersionMatchOnly) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 114
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass66_0.<IsTransitiveDependency>b__1(PackageDependency d) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 102
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass68_0.<ContainsDependency>b__1(PackageDependency d) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 140
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass68_0.<ContainsDependency>b__0(LockFileTargetLibrary l) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 140
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.ContainsDependency(TargetFrameworkMoniker tfm, Func`2 filter) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 140
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass66_0.<IsTransitiveDependency>b__0(TargetFrameworkMoniker tfm) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 102
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.IsTransitiveDependency(NuGetReference nugetReference) in /_/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/MSBuildProject.NuGetPackages.cs:line 102
   at Microsoft.DotNet.UpgradeAssistant.Steps.Packages.Analyzers.TransitiveReferenceAnalyzer.AnalyzeAsync(IProject project, PackageAnalysisState state, CancellationToken token) in /_/src/steps/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/Analyzers/TransitiveReferenceAnalyzer.cs:line 40
   at Microsoft.DotNet.UpgradeAssistant.Steps.Packages.PackageUpdaterStep.RunPackageAnalyzersAsync(IUpgradeContext context, CancellationToken token) in /_/src/steps/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/PackageUpdaterStep.cs:line 206
   at Microsoft.DotNet.UpgradeAssistant.Steps.Packages.PackageUpdaterStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token) in /_/src/steps/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/PackageUpdaterStep.cs:line 172
```

### Further technical details
- Windows 20H2 19042.928 (64-bit)
- `dotnet --list-sdks`

```
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.207 [C:\Program Files\dotnet\sdk]
3.1.300 [C:\Program Files\dotnet\sdk]
3.1.408 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]
```

- Include the output of `upgrade-assistant --version`

```
0.2.222702+aa9fd4e57ceef6ec3c09e585da50b2c0ba8986b4
```

**Comment by sunandabalu** [comment]
@valdisiljuconoks  Thank you for filing the issue, we have #393 to track adding support for allowed versions. Closing this as dupe.
