### ISSUE TITLE
Could not Load Microsoft.Build

### ISSUE THREAD

**Issue by jptemplin** [dotnet/upgrade-assistant#527]
I got blown out of the water pretty quickly when trying to convert the first project file in my solution (a small, one-file class library) to SDK format. Here are the relevant messages. I have both 32 and 64-bit 5.0.203 installed on my system. I've also attached the .csproj file it was trying to convert.
[PaprikaJSON.zip](https://github.com/dotnet/upgrade-assistant/files/6480236/PaprikaJSON.zip)

`PS G:\Convert Dev\Paprika Recipe Converter> dotnet msbuild --version
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
16.9.0.11203

-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.226201+4598a23e60b7571063570ee21e868f0f446b5b0f -
-----------------------------------------------------------------------------------------

[13:09:47 INF] MSBuild registered from C:\Program Files (x86)\dotnet\sdk\5.0.203\
[13:09:47 INF] Registered 1 extensions:
        Default extension
[13:09:48 INF] Loading upgrade progress file at G:\Convert Dev\Paprika Recipe Converter\.upgrade-assistant
[13:09:48 INF] Initializing upgrade step Back up project
[13:09:48 INF] Initializing upgrade step Convert project file to SDK style

[13:10:16 INF] Applying upgrade step Convert project file to SDK style
[13:10:16 INF] Converting project file format with try-convert, version 0.7.222801
[13:10:16 INF] [try-convert] System.BadImageFormatException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
[13:10:16 INF] [try-convert] File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[13:10:16 INF] [try-convert]    at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
[13:10:16 INF] [try-convert]    at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms) in /_/src/try-convert/Program.cs:line 102
[13:10:16 ERR] [try-convert] Error: Exited with non-success code: -1
[13:10:16 FTL] Conversion with try-convert failed.
[13:10:17 WRN] Upgrade step Convert project file to SDK style failed: Failed: Conversion with try-convert failed.
Command (Apply next step (Convert project file to SDK style)) did not succeed
`

**Comment by jptemplin** [comment]
Sorry, forgot: Windows 10 20H2 Build 19042.985
Visual Studio 2019 Community 16.9.4

**Comment by sunandabalu** [comment]
@jptemplin Looks like there is some weirdness going on between bit-ness of try-convert and upgrade-assistant, we will take a look. Thanks for filing the issue.

**Comment by jptemplin** [comment]
I have kept a copy of the solution directory, so I can provide any additional information you may need. Just ask. 

In the meantime, it was a small solution, so I went ahead and manually upgraded it because I needed to push out a new store version to fix a bug that I could only fix by using .NET 5. It would still be nice to run try-convert and compare it to my manual results to see if I upgraded correctly.

**Comment by sunandabalu** [comment]
I was unable to repro this in my local machine using the csproj you attached, setting up a vm to see if I can get a repro.

**Comment by sunandabalu** [comment]
So I cant repro this issue, this was what my logs say : 

```
2021-05-18 13:02:25.415 -07:00 [INF] MSBuild registered from C:\Program Files\dotnet\sdk\5.0.203\
2021-05-18 13:02:25.512 -07:00 [INF] Registered 1 extensions:
	Default extension
2021-05-18 13:02:25.828 -07:00 [WRN] Did not find a Visual Studio instance
2021-05-18 13:02:27.561 -07:00 [INF] Initializing upgrade step Select an entrypoint
2021-05-18 13:02:27.569 -07:00 [INF] Setting entrypoint to only project in solution: C:\Downloads\PaprikaJSON\PaprikaJSON.csproj
2021-05-18 13:02:27.580 -07:00 [INF] Initializing upgrade step Select project to upgrade
2021-05-18 13:02:27.670 -07:00 [INF] Initializing upgrade step Back up project
2021-05-18 13:02:45.940 -07:00 [INF] Skipping upgrade step Back up project
2021-05-18 13:02:45.950 -07:00 [INF] Upgrade step Back up project skipped
2021-05-18 13:02:47.123 -07:00 [INF] Initializing upgrade step Convert project file to SDK style
2021-05-18 13:02:49.390 -07:00 [INF] Applying upgrade step Convert project file to SDK style
2021-05-18 13:02:49.402 -07:00 [INF] Converting project file format with try-convert, version 0.7.222801
2021-05-18 13:02:51.187 -07:00 [INF] [try-convert] Conversion complete!
2021-05-18 13:02:51.346 -07:00 [INF] Project file converted successfully! The project may require additional changes to build successfully against the new .NET target.
```

I guess the only difference I see is that for you the MSBuild is being picked from your 32-bit installation while mine is picking from the 64-bit installation.

**Comment by jptemplin** [comment]
When I have a moment, I'll see if I can reproduce the issue on my other computer. I'm as confused as you are why the bitness isn't matching.

**Comment by jptemplin** [comment]
Well, I was not able to reproduce the problem on my other system. I had installed both 32 and 64 bit .NET 5 and my project converted cleanly. With some minor edits (adding references to .dll's in another solution), I built and ran the main executable in debug mode. 

I don't know what's different on my main dev system, but there could be accumulated cruft from the past year (my other system is a more bare-bones environment just enough to build my two store programs). You can close this if you like. Thanks for trying to recreate this.

**Comment by sunandabalu** [comment]
Thanks for re-trying @jptemplin , I'll close this for now. Feel free to re-open if this re-surfaces.

**Comment by leonbohmann** [comment]
I have the same issue. `BadImageFormatException` on `Microsoft.Build`. 
.NET x86 and x64 installed, try-convert and upgrade-assistant are installed. Win10 VS 16.9.6..
