### ISSUE TITLE
未能加载项目文件

### ISSUE THREAD

**Issue by konghao8013** [dotnet/upgrade-assistant#542]
Unexpected error during upgrade.
Microsoft.Build.Exceptions.InvalidProjectFileException: 未能加载项目文件。Data at the root level is invalid. Line 1, position 1.  D:\konghao\code\QDM\.net5\Hitek.QDM.WebAPI\Hitek.QDM.WebAPI\Hitek.QDM.WebAPI.csproj
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at Microsoft.Build.Internal.XmlReaderExtension.GetXmlReader(String file, StreamReader input, Boolean loadAsReadOnly, Encoding& encoding)
   at Microsoft.Build.Internal.XmlReaderExtension..ctor(String file, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)

**Comment by sunandabalu** [comment]
@konghao8013 Thanks for reporting the issue, Could you attach the csproj in question so we can see what is going on?

**Comment by brandonh-msft** [comment]
@konghao8013 if you're able to attach the project so we can debug further, please re-open. Thanks!
