### ISSUE TITLE
 An equivalent project (a project with the same global properties and tools version) is already present in the project collection

### ISSUE THREAD

**Issue by yehudahaber** [dotnet/upgrade-assistant#635]
Getting the below error when updated the startup project (last) of all the projects in the solution.
This is in the "Convert project file to SDK style" step

[19:58:24 INF] [dotnet]    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
[19:58:24 INF] [dotnet]    at Microsoft.Build.Evaluation.ProjectCollection.LoadedProjectCollection.AddProject(Project project)
[19:58:24 INF] [dotnet]    at Microsoft.Build.Evaluation.ProjectCollection.OnAfterRenameLoadedProject(String oldFullPathIfAny, Project project)
[19:58:24 INF] [dotnet]    at Microsoft.Build.Evaluation.Project.ProjectImpl.<Initialize>b__141_0(String oldFullPath)
[19:58:24 INF] [dotnet]    at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
[19:58:24 INF] [dotnet]    at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
[19:58:24 INF] [dotnet]    at MSBuild.Abstractions.UnconfiguredProject.LoadProjects(ProjectCollection collection, ProjectRootElement rootElement) in /_/src/MSBuild.Abstractions/UnconfiguredProject.cs:line 38
[19:58:24 INF] [dotnet]    at MSBuild.Abstractions.MSBuildConversionWorkspace.TryCreateSdkBaselineProject(String projectFilePath, IProject project, IProjectRootElement root, ImmutableDictionary`2 configurations, String tfm, Boolean keepCurrentTFMs, Nullable`1& baselineProject) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs:line 194
[19:58:24 INF] [dotnet]    at MSBuild.Abstractions.MSBuildConversionWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs:line 55
[19:58:24 INF] [dotnet]    at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb) in /_/src/MSBuild.Abstractions/MSBuildConversionWorkspaceLoader.cs:line 42
[19:58:24 INF] [dotnet]    at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms) in /_/src/try-convert/Program.cs:line 102
[19:58:24 ERR] [dotnet] Error: Exited with non-success code: -1

**Comment by sunandabalu** [comment]
@yehudahaber Could you share the csproj that you are running UA against?

**Comment by yehudahaber** [comment]
1100+ lines in redacted form...
[UpgradeAssistantFailed.zip](https://github.com/dotnet/upgrade-assistant/files/6697972/UpgradeAssistantFailed.zip)

**Comment by sunandabalu** [comment]
@yehudahaber Thanks for the csproj, we will take a look. This looks like a bug.

**Comment by isaacrlevin** [comment]
Is there an update here? 

cc @twsouthwick @cathysull

**Comment by yehudahaber** [comment]
This is still an issue using the newest version. Is there any guidance on how to get past this?
