### ISSUE TITLE
NuGet API throws MethodNotFound on some versions of .NET SDK

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#817]
### Describe the bug
We are compiling against a specific version of NuGet APIs, but are loading the runtime versions from the .NET SDK. With 5.0.400 of the SDK, the integration tests fail.

### To Reproduce
Run integration tests with .NET SDK v5.0.400

### Exceptions (if any)
```
fail: Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner[0]
      Unexpected error
      System.MissingMethodException: Method not found: 'NuGet.Frameworks.NuGetFramework NuGet.ProjectModel.LockFileTarget.get_TargetFramework()'.
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<>c__DisplayClass76_0.<GetAllPackageReferenceDependenciesAsync>b__1(LockFileTarget t)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.<GetAllPackageReferenceDependenciesAsync>g__GetLockFileTarget|76_0(NuGetFramework parsedTfm) in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 173
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetAllPackageReferenceDependenciesAsync(TargetFrameworkMoniker tfm, CancellationToken token)+MoveNext() in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 129
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetAllPackageReferenceDependenciesAsync(TargetFrameworkMoniker tfm, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at System.Linq.AsyncEnumerable.<AnyAsync>g__Core|211_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 58
         at System.Linq.AsyncEnumerable.<AnyAsync>g__Core|211_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 58
         at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 83
         at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 81
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.IsTransitivelyAvailableAsync(String packageName, CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.NuGetPackages.cs:line 72
         at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 83
         at System.Linq.AsyncEnumerable.<AnyAwaitAsyncCore>g__Core|212_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Any.cs:line 81
         at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.WindowsComponentIdentifier.GetComponentsAsync(IProject project, CancellationToken token)
         at Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildProject.GetComponentsAsync(CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant.MSBuild\MSBuildProject.cs:line 114
         at Microsoft.DotNet.UpgradeAssistant.Extensions.Maui.MauiPlatformTargetFrameworkUpgradeStep.IsApplicableImplAsync(IUpgradeContext context, CancellationToken token)
         at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.IsApplicableAsync(IUpgradeContext context, CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\common\Microsoft.DotNet.UpgradeAssistant.Abstractions\UpgradeStep.cs:line 223
         at Microsoft.DotNet.UpgradeAssistant.UpgraderManager.<>c__DisplayClass9_0.<<GetStepsForContextAsync>b__0>d.MoveNext() in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant\UpgraderManager.cs:line 168
      --- End of stack trace from previous location ---
         at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIteratorWithTaskAndCancellation`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:line 339
         at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
         at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
         at System.Linq.AsyncEnumerable.<AllAsync>g__Core|207_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/All.cs:line 34
         at System.Linq.AsyncEnumerable.<AllAsync>g__Core|207_0[TSource](IAsyncEnumerable`1 source, Func`2 predicate, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/All.cs:line 34
         at Microsoft.DotNet.UpgradeAssistant.UpgraderManager.GetNextStepAsync(IUpgradeContext context, CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\components\Microsoft.DotNet.UpgradeAssistant\UpgraderManager.cs:line 76
         at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\Commands\Upgrade\ConsoleUpgrade.cs:line 70
         at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleUpgrade.RunAsync(CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\Commands\Upgrade\ConsoleUpgrade.cs:line 79
         at Microsoft.DotNet.UpgradeAssistant.Cli.ConsoleRunner.StartAsync(CancellationToken token) in E:\Work\migration\UpgradeAssistant\src\cli\Microsoft.DotNet.UpgradeAssistant.Cli\ConsoleRunner.cs:line 62
```

**Comment by twsouthwick** [comment]
I'm going to look at moving the NuGet related usage into an extension then it'll load in its own AssemblyLoadContext and we won't be subjected to these kind of errors
