### ISSUE TITLE
How to use --entry-point option?

### ISSUE THREAD

**Issue by Nadare2012** [dotnet/upgrade-assistant#846]
Hello, I am trying to upgrade solution with many projects, starting from specific project (entry point). I tried to use --entry-point options with many arguments: full path to csproj file, relative path to csproj file, project name, project number (from selection step), but all of them was ignored.

For example: create solution with 2 console applications. Typing ```upgrade-assistant upgrade ConsoleApplication1.sln -e C:\src\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.csproj``` does not select ConsoleApplication1 project as entry point.

**Comment by Nadare2012** [comment]
Specifying csproj filename worked (ConsoleApplication1.csproj)
```upgrade-assistant upgrade ConsoleApplication1.sln -e ConsoleApplication1.csproj```

I think throwing an exception when the entry point is not recognized would be better than ignoring argument.

**Comment by sunandabalu** [comment]
> I think throwing an exception when the entry point is not recognized would be better than ignoring argument.

@Nadare2012 Thanks, this is a good suggestion to incorporate.

**Comment by MisinformedDNA** [comment]
I can't get it to work. Specifying the project filename (or other variations) hasn't helped. Always this same exception:

> upgrade-assistant upgrade SomeSolution.sln -e SomeProject.csproj
> Unhandled exception. System.ArgumentException: Type System.Collections.Generic.IReadOnlyCollection`1[System.String] cannot be created without a custom binder.
>    at System.CommandLine.Binding.ArgumentConverter.CreateEnumerable(Type type, Type itemType, Int32 capacity)
>    at System.CommandLine.Binding.ArgumentConverter.ConvertTokens(Argument argument, Type type, IReadOnlyList`1 tokens, LocalizationResources localizationResources, ArgumentResult argumentResult)
>    at System.CommandLine.Binding.ArgumentConverter.TryConvertArgument(ArgumentResult argumentResult, Object& value)
>    at System.CommandLine.Parsing.ArgumentResult.Convert(Argument argument)
>    at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
>    at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
>    at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertOptionResult(OptionResult optionResult)
>    at System.CommandLine.Parsing.ParseResultVisitor.Stop()
>    at System.CommandLine.Parsing.ParseResultVisitor.Visit(SyntaxNode node)
>    at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
>    at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
>    at Microsoft.DotNet.UpgradeAssistant.Cli.Program.<Main>(String[] args)
